name: manual_test_pip

on:
  workflow_dispatch:
    inputs:
      install_prerelease:
        description: 'Check this to install the prerelease version of medspacy if available and the version is newer than formal release.'  
        type: boolean   
        required: false
        default: false
      python_versions:
        description: 'Python versions to build (JSON array)'
        default: '["3.8", "3.9", "3.10.x", "3.11.x", "3.12.x", "3.13.x"]'
        required: true        

jobs:

  test:
  
    # TODO: Do we care if this only runs on allowed branches since we check push/pull_request above?
    #if: github.ref == 'refs/heads/master' OR github.ref == 'refs/heads/develop'

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # python-version: [3.8]
        python-version: ${{ fromJSON(github.event.inputs.python_versions) }}
        # revised from https://github.com/actions/cache/blob/main/examples.md#python---pip
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Git clone repo and remove source code
      shell: bash
      run: |
        pwd
        ls
        # remove cloned source code to ensure test on installed medspacy
        python -c "import shutil;shutil.rmtree('src')"
        ls
        rm *.pyx

    - name: Set up pip
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}   
        cache: 'pip'

    - run: |
        python --version
        pip install --upgrade pip
    
    
    - name: Install prereleased medspacy
      if: ${{ github.event.inputs.install_prerelease == 'true' }} 
      run: |
        # use this to avoid install prereleases of dependencies packages
        pip install --pre medspacy-unqlite

    - name: Install formal released medspacy
      if: ${{ github.event.inputs.install_prerelease == 'false' }}  
      run: |
        pip install medspacy-unqlite

   

    
    - name: Test 
      # need to run pytest after a clean pip install to 100% replicate the users' environment
      run: |        
        python test.py